### PR TITLE
Converted space indentation to tab indentation

### PR DESCRIPTION
**Pull request by demhydraz**
This patch will convert all sequences of 4 spaces in the source tree anchored to `^` into an appropriate number of hard tabs.

### CODE REVIEW

**Comment by viluon** [comment]
How did spaces even happen?

**Comment by demhydraz** [comment]
Sublime *giggles*

**Comment by viluon** [comment]
@demhydraz believe it or not, default indentation in Sublime is tabs, and it can convert tabs to spaces and vice versa very easily. I am using it too.

**Comment by SquidDev** [comment]
@oeed Have you considered adding an [editorconfig](http://editorconfig.org/) file?

**Comment by demhydraz** [comment]
@viluon that's what @oeed told me, it happened because of bad-editor-syndrome

**Comment by oeed** [comment]
For some reason I my settings had tabs converting to spaces... no idea why.

**Pull request merged**
